# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM openjdk:8-alpine

ARG DISTRO_TAR
ARG DISTRO_NAME

USER root

COPY entrypoint.sh $DISTRO_TAR /opt/

RUN cd /opt && tar xzf $DISTRO_TAR && ln -s $DISTRO_NAME spark && rm $DISTRO_TAR && \
    apk upgrade --no-cache && \
    apk add --no-cache bash tini && \
    touch /opt/spark/RELEASE && \
    chgrp -R root /opt && \
    chmod -R ug+rwx /opt && \
    chgrp root /etc/passwd && \
    chmod ug+rw /etc/passwd

ENV PATH=$PATH:/opt/spark/bin SPARK_HOME=/opt/spark JAVA_HOME=${JAVA_HOME:-/usr}

WORKDIR /opt/spark

ENTRYPOINT [ "/opt/entrypoint.sh" ]
