#!/bin/sh

#echo "sleeping..." >&2
#sleep 36000

. /common.sh

# run the spark master directly (instead of sbin/start-master.sh) to
# link master and container lifecycle
exec spark-class org.apache.spark.deploy.master.Master
