#!/bin/sh

master=$1

if [ -z "$master" ]; then
  echo "No master provided, e.g. spark://spark-master.local:7077" >&2
  exit 1
fi

#echo "sleeping..." >&2
#sleep 36000

. /common.sh

echo "Starting worker, will connect to: $master"
spark-class org.apache.spark.deploy.worker.Worker $master
