#!/bin/sh

master=$1

if [ -z "$master" ]; then
  echo "No master provided, e.g. spark://spark-master.local:7077" >&2
  exit 1
fi

# spin up shuffle service on worker nodes
echo "Starting shuffle service"
$SPARK_HOME/sbin/start-shuffle-service.sh

echo "Starting worker, will connect to: $master"

. /common.sh

spark-class org.apache.spark.deploy.worker.Worker $master
